# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=4.0.x-dev
    - CORE_RELEASE=master

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1.2
      env: DB=MYSQL PDO=1 PHPUNIT_COVERAGE_TEST=1

before_script:
  - composer validate
  - composer self-update || true
  - "if [ \"$PHPCS_TEST\" = \"1\" ]; then composer require --dev squizlabs/php_codesniffer; fi"
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer install --prefer-dist

script:
  - "if [ \"$PHPUNIT_TEST\" = \"1\" ]; then vendor/bin/phpunit; fi"
  - "if [ \"$PHPCS_TEST\" = \"1\" ]; then composer run-script lint; fi"
  - "if [ \"$PHPUNIT_COVERAGE_TEST\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi"

after_success:
  - "if [ \"$PHPUNIT_COVERAGE_TEST\" = \"1\" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi"
